### PR TITLE
Code rewritten - initial commit

### PR DESCRIPTION
**Pull request by Eiji7**
TODO:
1. AI (random decisions: attack or move - or both if config actions > 1)
2. Stop game at flag captured.

### CODE REVIEW

**Comment by Hal9000** [comment]
Why did you close this?

**Comment by Hal9000** [comment]
I was trying to figure out how to resolve the conflicts and merge.

**Comment by Eiji7** [comment]
I'm doing this now

**Comment by Hal9000** [comment]
Gotcha, thx

**Comment by Eiji7** [comment]
Done, see [new PR](https://github.com/Hal9000/vexil/pull/3)

**Pull request closed without merging**
